export const FETCH_USERS = 'FETCH_USERS'
export const USERS_FETCH_PROGRESS = 'USERS_FETCH_PROGRESS'
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE'
